### ISSUE TITLE
Support Privacy Manifest

### ISSUE THREAD

**Issue by hakburi** [shoplive/ios-sdk#4]
안녕하세요!

2024년 봄부터 Apple은 Third-Party SDK에 Privacy Manifest 파일을 추가하도록 요구합니다.

https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

ShopLive SDK 에서는 Privacy Manifest 가 안필요한가요?
필요하다면 언제 추가할 계획이 있나요?

**Comment by hassan0424** [comment]
안녕하세요. 
Shoplive iOS 개발자 Hassan입니다.
다음주에 Privacy manifest file이 첨부된 sdk 배포와 전체적으로 알림 메일 보내도록 예정되어있습니다.
감사합니다.

**Comment by hassan0424** [comment]
안녕하세요.
최근 1.5.7에서 privacy manifest file이 추가되어 배포되었습니다.
해당 버전 사용하시면 될 것 같습니다.
감사합니다.
